---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r}
rm(list = ls())
library(rvest)
library(dplyr)
justiceLink = "https://www.justice.gov/ust/eo/bapcpa/20191101/bci_data/median_income_table.htm"
justicePage <- read_html(justiceLink)
```
```{r}
(state <- justicePage %>% html_nodes("tr~ tr+ tr .mitable") %>% html_text()) # state column 
```
```{r}
(state <- state[-c(1,53)]) # rows 1 and 53
```
```{r}
row.names(state)=NULL #gets rid of blanks?
state
```
```{r}
state = state[-c(52:55)]
```

```{r}
oneEarner <- justicePage %>% html_nodes(".mitable+ .mitablenum") %>% html_text() # subsetting one earner income
```
```{r}
oneEarner =oneEarner[-c(1,53)]
```
```{r}
oneEarner = oneEarner[-c(52:55)]
```
```{r}
myIncomeData <- data.frame(state, oneEarner) #, stringAsFactors = FALSE) # new data frame with items we want
```
```{r}
#myIncomeData=myIncomeData[-c(52,53,55),] # removing items we don't want 
```
```{r}
(myIncomeData %>% 
 # desc orders from largest to smallest
  arrange(desc(oneEarner)) %>%
 # select subsets the columns you want
 select(state, oneEarner))
```

```

